### ISSUE TITLE
css 居中

### ISSUE THREAD

**Issue by soonfy** [soonfy/issue-blog#11]
# css 居中
`css 居中还有很多，以后慢慢补充`

## 水平居中

1. 内联元素（文本）水平居中
```css
.inline-item {
  text-align: center;
}
```

2. 块级元素水平居中
```css
.block-item {
  margin: 0 auto;
}
```

3. 多个块级元素水平居中
- **text-align** + **display**
```css
.container {
  text-align: center;
}
.block-item {
  display: inline-block;
}
```

- **flex**
```css
.container {
  display: flex;
  justify-content: center;
}
```

## 垂直居中

1. 单行内联元素（文本）垂直居中
```css
.container {
  height: 100px;
  line-height: 100px;
}
```

2. 多行元素垂直居中

- **table**
```css
.container {
  display: table;
}
.item {
  display: table-cell;
  vertical-align: middle;
}
```

- **flex**
```css
.container {
  display: flex;
  align-items: center;
}
or
.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
```

3. 块级元素垂直居中

- 固定高度的块级元素垂直居中
```css
.container {
  position: relative;
}
.item {
  position: absolute;
  top: 50%;
  height: 120px;
  margin-top: -60px;
}
```

- 未知高度的块级元素垂直居中
```css
.container {
  position: relative;
}
.item {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```

## 水平垂直居中

1. 固定宽度和高度的元素水平垂直居中
```css
.container {
  position: relative;
}
.item {
  width: 400px;
  height: 300px;
  padding: 20px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin: -160px 0 0 -210px;
}
```

2. 未知高度和宽度的元素水平垂直居中
```css
.container {
  position: relative;
}
.item {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

3. flex 布局
```css
.container {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

**参考文章**

[这15种CSS居中的方式，你都用过哪几种？](http://www.42du.cn/paper/46)

soonfy
2018-04-03
