### ISSUE TITLE
weui grid

### ISSUE THREAD

**Issue by soonfy** [soonfy/issue-blog#42]
### 默认九宫格

```css
.weui-grid {
  width: 33.3333333%;
}
```

### 转换为N宫格
> 覆盖 .weui-grid 的 width 属性

```css
.weui-grid {
  width: 50%;
}
```

soonfy
